version: "3.4"

services:
  webapp:
    build: .
    volumes:
      - type: bind
        source: ./project
        target: /opt/services/webapp/src
      - type: volume
        source: static_volume
        target: /opt/services/webapp/static
      - type: volume
        source: media_volume
        target: /opt/services/webapp/media
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.17.4
    volumes:
      - type: bind
        source: ./config/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: static_volume
        target: /opt/services/webapp/static
      - type: volume
        source: media_volume
        target: /opt/services/webapp/media
    ports:
      - 8000:80
    depends_on:
      - webapp
    networks:
      - nginx_network

  database1:
    image: postgres:12.0
    env_file:
      - ./config/db/database1_env
    networks:
      - database1_network
    volumes:
      - type: volume
        source: app_data
        target: /var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  app_data:
  static_volume:
  media_volume:
